language: scala
sudo: false
env:
  global:
# Don't commit sensitive files, instead commit a version encrypted with $SECRET,
# this environment variable is encrypted with this repo's private key and stored below:
# (See http://docs.travis-ci.com/user/environment-variables/#Secure-Variables.)
    - secure: "YO/7YiWEirzz0EAy7oVNmAKroj4qCLZNMkPS+xW/VgeGjuEV+Nk1S7pwxF0o2OggSxIQ+a0lWSrOPQqSXMjOstDIzzGeYfuAt0+0fupXtDDge0mXpCCMadrvYzff1/5XYX0dJ+pjJmz6IgF1hliPJHIuddhhdqPxdHWTHAKm9ME="

script:
  - admin/build.sh
matrix:
  include:
  - scala: 2.11.8
    jdk: openjdk6
    env: IS_PUBLISH_JDK=true
  - scala: 2.11.8
    jdk: oraclejdk8
  - scala: 2.12.0
    jdk: oraclejdk8
    env: IS_PUBLISH_JDK=true
notifications:
  email:
    - jason.zaugg@typesafe.com
    - philipp.haller@typesafe.com
